// Generated by GitHub Copilot
/**
 * MyISP Tools - API Configuration
 * 
 * This file configures the backend API URL for all tools.
 * 
 * When running locally:
 *   - Set API_BASE_URL to '' (empty string) or 'http://localhost:5000'
 * 
 * When deployed to GitHub Pages:
 *   - Set API_BASE_URL to your deployed backend URL (e.g., Render.com)
 *   - Example: 'https://myisp-tools.onrender.com'
 */

// ============================================================================
// CONFIGURATION
// ============================================================================

/**
 * Backend API base URL
 * 
 * OPTIONS:
 * 1. Local development: '' or 'http://localhost:5000'
 * 2. Render.com deployment: 'https://myisp-tools.onrender.com'
 * 3. Azure deployment: 'https://myisp-tools.azurewebsites.net'
 * 4. Custom server: 'http://your-server-ip:5000'
 */
const API_BASE_URL = 'https://myisp-functionalteam.onrender.com'; // Production backend on Render.com

// ============================================================================
// HELPER FUNCTION
// ============================================================================

/**
 * Constructs full API endpoint URL
 * @param {string} endpoint - API endpoint path (e.g., '/api/generate-report')
 * @returns {string} Full URL to the API endpoint
 */
function getApiUrl(endpoint) {
    // Remove leading slash if present to avoid double slashes
    const cleanEndpoint = endpoint.startsWith('/') ? endpoint : '/' + endpoint;
    
    // If API_BASE_URL is empty, return relative path (for local development)
    if (!API_BASE_URL || API_BASE_URL === '') {
        return cleanEndpoint;
    }
    
    // Remove trailing slash from base URL to avoid double slashes
    const cleanBaseUrl = API_BASE_URL.endsWith('/') 
        ? API_BASE_URL.slice(0, -1) 
        : API_BASE_URL;
    
    return cleanBaseUrl + cleanEndpoint;
}

// ============================================================================
// DEPLOYMENT INSTRUCTIONS
// ============================================================================
// 
// TO DEPLOY:
// 
// 1. Deploy Flask backend to Render.com:
//    - Go to https://render.com
//    - Connect your GitHub repository
//    - Render will detect render.yaml and deploy automatically
//    - Copy your deployed URL (e.g., https://myisp-tools.onrender.com)
// 
// 2. Update this file:
//    - Set API_BASE_URL = 'your-deployed-url'
//    - Example: API_BASE_URL = 'https://myisp-tools.onrender.com'
// 
// 3. Commit and push to GitHub:
//    - git add config.js
//    - git commit -m "Update API URL for deployment"
//    - git push
// 
// 4. GitHub Pages will auto-update with new configuration
// 
// ============================================================================
