-- ============================================================
-- MyISP Tools – Supabase Database Schema
-- Run this SQL in the Supabase SQL Editor (supabase.com)
-- ============================================================

-- Generated by GitHub Copilot

-- ------------------------------------------------------------
-- 1. Authorized Users  (replaces Attendance/Access.csv)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS authorized_users (
    id          BIGSERIAL PRIMARY KEY,
    username    TEXT NOT NULL UNIQUE,        -- Windows username (lowercase)
    email       TEXT,
    role        TEXT DEFAULT 'member',       -- 'admin' | 'lead' | 'member'
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- 2. Team Members  (replaces Attendance/Team Details.xlsx)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_members (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT NOT NULL,
    lead        TEXT NOT NULL DEFAULT '',
    location    TEXT NOT NULL DEFAULT '',
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ------------------------------------------------------------
-- 3. Attendance Records  (replaces Master_Attendance.xlsx)
--    One row per member × day × month/year
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance_records (
    id          BIGSERIAL PRIMARY KEY,
    member_name TEXT NOT NULL,
    lead_name   TEXT NOT NULL DEFAULT '',
    location    TEXT NOT NULL DEFAULT '',
    year        SMALLINT NOT NULL,
    month       SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    day         SMALLINT NOT NULL CHECK (day BETWEEN 1 AND 31),
    status      TEXT NOT NULL DEFAULT '',   -- P, VG, VR, SL, MH, OP, etc.
    updated_at  TIMESTAMPTZ DEFAULT now(),
    UNIQUE (member_name, year, month, day)
);

-- Index for fast per-month queries
CREATE INDEX IF NOT EXISTS idx_attendance_year_month
    ON attendance_records (year, month);

CREATE INDEX IF NOT EXISTS idx_attendance_member
    ON attendance_records (member_name);

-- ------------------------------------------------------------
-- 4. Attendance Logs  (replaces Master_Attendance_Logs.xlsx)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attendance_logs (
    id           BIGSERIAL PRIMARY KEY,
    saved_at     TIMESTAMPTZ DEFAULT now(),
    user_id      TEXT NOT NULL DEFAULT '',
    lead_name    TEXT NOT NULL DEFAULT '',
    member_name  TEXT NOT NULL DEFAULT '',
    location     TEXT NOT NULL DEFAULT '',
    month_name   TEXT NOT NULL DEFAULT '',
    year         SMALLINT NOT NULL,
    day          SMALLINT,
    old_value    TEXT DEFAULT '',
    new_value    TEXT DEFAULT '',
    changed      TEXT DEFAULT '',           -- 'YES' | 'NO' | 'SYNC'
    sheet_name   TEXT DEFAULT '',
    client_ip    TEXT DEFAULT ''
);

-- Index for querying recent logs
CREATE INDEX IF NOT EXISTS idx_logs_saved_at
    ON attendance_logs (saved_at DESC);

-- ------------------------------------------------------------
-- Row Level Security (RLS)
-- Enable RLS but allow all operations via the service role key.
-- Tighten policies here once you add Supabase Auth users.
-- ------------------------------------------------------------
ALTER TABLE authorized_users   ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members       ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs    ENABLE ROW LEVEL SECURITY;

-- Allow full access via the anon key (app uses the anon key directly).
-- Replace with stricter policies once authentication is wired to Supabase Auth.
CREATE POLICY "allow_all_authorized_users"   ON authorized_users   FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_team_members"       ON team_members       FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_attendance_records" ON attendance_records FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_attendance_logs"    ON attendance_logs    FOR ALL USING (true) WITH CHECK (true);
