"""
supabase_client.py
──────────────────
Initialises the Supabase client from environment variables (.env file or
OS-level env vars) and exposes a ready-to-use `supabase` singleton.

Usage anywhere in the project:
    from supabase_client import supabase
    data = supabase.table('attendance_records').select('*').execute()
"""

# Generated by GitHub Copilot
import os
from dotenv import load_dotenv
from supabase import create_client, Client

# Load .env if present (safe no-op if the file doesn't exist)
load_dotenv()

_url: str = os.environ.get("SUPABASE_URL", "")
_key: str = os.environ.get("SUPABASE_ANON_KEY", "")

if not _url or not _key:
    raise EnvironmentError(
        "SUPABASE_URL and SUPABASE_ANON_KEY must be set. "
        "Copy .env.example → .env and fill in your project credentials."
    )

# Singleton Supabase client — re-used across all requests
supabase: Client = create_client(_url, _key)
