# Generated by GitHub Copilot
<#
.SYNOPSIS
    Updates all HTML files to use config.js for API endpoint configuration

.DESCRIPTION
    This script modifies all HTML files in the MyISP Tools project to:
    1. Include the config.js script
    2. Replace hardcoded /api/ fetch calls with getApiUrl() wrapper
    
    This enables the frontend to work with both local Flask backend and 
    deployed backend on Render.com/Azure/Heroku.

.NOTES
    Author: GitHub Copilot
    Date: 2026-04-10
    
.EXAMPLE
    .\Update-HtmlForDeployment.ps1
#>

# Change to script directory
Set-Location $PSScriptRoot

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  MyISP Tools - HTML Deployment Updater" -ForegroundColor Cyan  
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# List of HTML files to update
$htmlFiles = @(
    'index.html',
    'hotfix-daily-report.html', 
    'regression-report.html',
    'tc-compare-report.html',
    'm-poc-extref.html',
    'ado-testcase-upload.html',
    'ai-data-transfer.html',
    'missing-data-scope-report.html',
    'missing-filed-report.html',
    'attendance-report.html',
    'defect-status-report.html'
)

$updatedCount = 0
$alreadyUpdatedCount = 0
$notFoundCount = 0

foreach ($file in $htmlFiles) {
    $path = Join-Path $PSScriptRoot $file
    
    if (-not (Test-Path $path)) {
        Write-Host "  [WARN] $file - Not found, skipping" -ForegroundColor Yellow
        $notFoundCount++
        continue
    }
    
    $content = Get-Content $path -Raw -Encoding UTF8
    $originalContent = $content
    
    # Check if already updated
    $configCheck = '<script src="config.js"></script>'
    if ($content.Contains($configCheck)) {
        Write-Host "  [OK] $file - Already updated" -ForegroundColor Gray
        $alreadyUpdatedCount++
        continue
    }
    
    Write-Host "  [>>>] Updating $file..." -ForegroundColor Yellow
    
    # Step 1: Add config.js before first <script> tag
    if ($content -match '(?s)(.+?)<script>') {
        $beforeScript = $matches[1]
        $afterScript = $content.Substring($beforeScript.Length)
        
        # Add config.js include
        $content = $beforeScript + '<script src="config.js"></script>' + "`n" + $afterScript
    }
    
    # Step 2-4: Update all fetch('/api/...) variations
    # Using simpler string replacement approach
    $content = $content -replace 'fetch\(''(/api/', 'fetch(getApiUrl(''$1'
    $content = $content -replace 'fetch\("(/api/', 'fetch(getApiUrl("$1'
    $content = $content -replace 'fetch\(`(/api/', 'fetch(getApiUrl(`$1'
    
    # Only save if content changed
    if ($content -ne $originalContent) {
        Set-Content $path -Value $content -NoNewline -Encoding UTF8
        Write-Host "  [OK] $file - Successfully updated" -ForegroundColor Green
        $updatedCount++
    } else {
        Write-Host "  [  ] $file - No changes needed" -ForegroundColor Gray
        $alreadyUpdatedCount++
    }
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Summary" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Updated:          $updatedCount files" -ForegroundColor Green
Write-Host "  Already updated:  $alreadyUpdatedCount files" -ForegroundColor Gray
Write-Host "  Not found:        $notFoundCount files" -ForegroundColor Yellow
Write-Host ""

if ($updatedCount -gt 0) {
    Write-Host "[SUCCESS] HTML files updated successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Deploy Flask backend to Render.com" -ForegroundColor White
    Write-Host "  2. Update config.js with your deployed URL" -ForegroundColor White
    Write-Host "  3. Test locally: python app.py" -ForegroundColor White
    Write-Host "  4. Commit and push to GitHub" -ForegroundColor White
    Write-Host ""
    Write-Host "See GITHUB_PAGES_FIX.md for detailed instructions" -ForegroundColor Cyan
} else {
    Write-Host "[INFO] All files were already up to date" -ForegroundColor Cyan
}

Write-Host ""
