# Generated by GithubCopilot
# Downloads the Release Excel file from SharePoint (mySPTesting site) to the local output directory.
#
# Uses Microsoft Edge in HEADLESS mode (no visible browser window).
# Edge leverages Windows Integrated Authentication (SSO) on corporate machines
# so no username/password prompt is needed.
#
# Works on corporate networks WITHOUT internet access – uses the msedgedriver.exe
# that is bundled with your Edge installation (no download required).
#
# Requires:
#   pip install selenium

import os
import warnings
import time
import glob
from pathlib import Path
from urllib.parse import quote

# Prevent Selenium Manager from making internet requests (blocked on corporate network)
os.environ.setdefault("SE_AVOID_BROWSER_DOWNLOAD", "1")
os.environ.setdefault("SE_MANAGER_PATH", "")

# Suppress urllib3/chardet version mismatch warning from requests package
warnings.filterwarnings("ignore", message="urllib3", category=UserWarning)
warnings.filterwarnings("ignore", category=Warning, module="requests")

from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.edge.options import Options

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Get the directory where this script is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Directory where the downloaded file will be saved
OUTPUT_DIR = SCRIPT_DIR

SITE_URL = "https://ts.accenture.com/sites/mySPTesting"

# Server-relative path to the folder containing the release Excel file
FILE_FOLDER_RELATIVE_URL = "/sites/mySPTesting/Shared Documents/General/01 - Deliverables/Releases - FY 2025-2026/May"
FILE_NAME_BASE = "May 9th_Release"
EXCEL_EXTENSIONS = [".xlsx", ".xlsm", ".xls", ".xlsb"]

# Canonical name to rename the downloaded file to (so callers always find it by this name)
CANONICAL_FILENAME = "PT Status excel.xlsx"

# How many seconds to wait for the download to finish
DOWNLOAD_TIMEOUT = 60


# ---------------------------------------------------------------------------
# Edge browser helpers
# ---------------------------------------------------------------------------

def find_local_msedgedriver() -> str | None:
    """
    Locate msedgedriver.exe that ships alongside the installed Edge browser.
    Searches the standard Edge installation directories on Windows.
    Returns the full path if found, otherwise None.
    """
    search_roots = [
        r"C:\Program Files (x86)\Microsoft\Edge\Application",
        r"C:\Program Files\Microsoft\Edge\Application",
        os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\Edge\Application"),
        os.path.expandvars(r"%PROGRAMFILES%\Microsoft\Edge\Application"),
        os.path.expandvars(r"%PROGRAMFILES(X86)%\Microsoft\Edge\Application"),
    ]
    
    print("Searching for msedgedriver.exe in:")
    for root in search_roots:
        print(f"  - {root}")
        if not os.path.isdir(root):
            print(f"    (directory not found)")
            continue
        
        # Try direct path first (faster)
        direct_path = os.path.join(root, "msedgedriver.exe")
        if os.path.exists(direct_path):
            print(f"    ✓ Found: {direct_path}")
            return direct_path
        
        # Search recursively in version subdirectories
        try:
            for candidate in Path(root).rglob("msedgedriver.exe"):
                print(f"    ✓ Found: {candidate}")
                return str(candidate)
        except Exception as e:
            print(f"    Error searching: {e}")
    
    print("  ✗ msedgedriver.exe not found in any location")
    return None


def find_edge_binary() -> str | None:
    """
    Locate the Edge browser executable (msedge.exe).
    Returns the full path if found, otherwise None.
    """
    search_paths = [
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\Edge\Application\msedge.exe"),
        os.path.expandvars(r"%PROGRAMFILES%\Microsoft\Edge\Application\msedge.exe"),
        os.path.expandvars(r"%PROGRAMFILES(X86)%\Microsoft\Edge\Application\msedge.exe"),
    ]
    for path in search_paths:
        if os.path.exists(path):
            return path
    return None


def build_edge_driver() -> webdriver.Edge:
    """
    Build and return a headless Edge WebDriver configured to:
      - Run completely in the background (no visible window)
      - Download files silently to OUTPUT_DIR (no Save-As dialog)
      - Use Windows Integrated Authentication (SSO) automatically
    """
    options = Options()

    # ── Find Edge binary explicitly ──────────────────────────────────────
    edge_binary = find_edge_binary()
    if edge_binary:
        print(f"Found Edge browser: {edge_binary}")
        options.binary_location = edge_binary
    else:
        print("Warning: Could not locate Edge browser executable")

    # ── Headless mode: no visible browser window ──────────────────────────
    options.add_argument("--headless=new")
    options.add_argument("--window-size=1920,1080")
    
    # Additional stability arguments
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-gpu")
    options.add_argument("--disable-software-rasterizer")
    options.add_argument("--disable-extensions")
    options.add_argument("--disable-blink-features=AutomationControlled")

    # Suppress the Save-As dialog and force download to OUTPUT_DIR
    prefs = {
        "download.default_directory": OUTPUT_DIR,
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "safebrowsing.enabled": True,
        "plugins.always_open_pdf_externally": True,
    }
    options.add_experimental_option("prefs", prefs)

    # Allow Windows Integrated Authentication (Kerberos/NTLM) for Accenture SSO
    options.add_argument("--auth-server-whitelist=*.accenture.com,*.ts.accenture.com")
    options.add_argument("--auth-negotiate-delegate-whitelist=*.accenture.com")

    # Suppress infobars and unnecessary notifications
    options.add_experimental_option("excludeSwitches", ["enable-automation", "enable-logging"])
    options.add_argument("--disable-notifications")
    options.add_argument("--no-first-run")
    options.add_argument("--log-level=3")  # Suppress verbose logs

    driver_path = find_local_msedgedriver()
    if driver_path:
        print(f"✓ Using local msedgedriver: {driver_path}")
        service = Service(driver_path, log_output=os.devnull)  # Suppress driver logs
    else:
        print("\n" + "="*80)
        print("ERROR: msedgedriver.exe not found!")
        print("="*80)
        print("\nCannot download SharePoint files without Edge driver.")
        print("\nSolution 1: Update Edge browser (includes driver)")
        print("  1. Open Edge: edge://settings/help")
        print("  2. Let it update to latest version")
        print("  3. Restart Edge")
        print("  4. Run this script again")
        print("\nSolution 2: Download driver manually")
        print("  1. Go to: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/")
        print("  2. Download matching your Edge version")
        print("  3. Extract to: C:\\Program Files\\Microsoft\\Edge\\Application\\")
        print("\nSolution 3: Use existing Excel files")
        print("  If files already exist, the main script will use them.")
        print("="*80 + "\n")
        raise RuntimeError("msedgedriver.exe not found. Cannot proceed with SharePoint download.")
    
    try:
        driver = webdriver.Edge(service=service, options=options)
        return driver
    except Exception as e:
        print(f"\nError creating Edge WebDriver: {e}")
        print("\nTroubleshooting steps:")
        print("1. Check Edge browser version: edge://version")
        print("2. Ensure Edge is updated to latest version")
        print("3. Try running: pip install --upgrade selenium")
        print("4. If behind corporate firewall, check if WebDriver Manager can download drivers")
        raise


def wait_for_download(before_files: set, timeout: int = DOWNLOAD_TIMEOUT) -> str | None:
    """
    Wait until a brand-new Excel file finishes downloading to OUTPUT_DIR.

    Strategy:
      1. Keep looping until there are no .crdownload / .tmp partial files left
         (meaning Edge has finished writing the final file).
      2. Then look for any Excel file that was NOT in before_files.

    Returns the full path of the downloaded file, or None on timeout.
    """
    deadline = time.time() + timeout
    download_seen = False

    while time.time() < deadline:
        partials = (
            glob.glob(os.path.join(OUTPUT_DIR, "*.crdownload")) +
            glob.glob(os.path.join(OUTPUT_DIR, "*.tmp"))
        )

        if partials:
            download_seen = True
            time.sleep(1)
            continue

        # No partials – look for a new completed Excel file
        for ext in EXCEL_EXTENSIONS:
            for f in glob.glob(os.path.join(OUTPUT_DIR, f"*{ext}")):
                if f not in before_files:
                    return f

        if download_seen:
            time.sleep(0.5)
            for ext in EXCEL_EXTENSIONS:
                for f in glob.glob(os.path.join(OUTPUT_DIR, f"*{ext}")):
                    if f not in before_files:
                        return f
            return None  # partials gone but no new file – likely failed

        time.sleep(1)

    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 70)
    print("SHAREPOINT FILE DOWNLOADER  (Headless Edge / Windows SSO)")
    print("=" * 70)
    print(f"\nSharePoint folder : {FILE_FOLDER_RELATIVE_URL}")
    print(f"File              : {FILE_NAME_BASE}.xlsx")
    print(f"Destination       : {OUTPUT_DIR}\n")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Clean up any stale partial files from previous failed runs
    for stale in glob.glob(os.path.join(OUTPUT_DIR, "*.crdownload")):
        try:
            os.remove(stale)
            print(f"Removed stale partial file: {os.path.basename(stale)}")
        except OSError:
            pass

    # Snapshot of files present before download
    before = set(
        f for ext in EXCEL_EXTENSIONS
        for f in glob.glob(os.path.join(OUTPUT_DIR, f"*{ext}"))
    )

    driver = None
    try:
        print("Starting headless Edge (no window will open) ...")
        driver = build_edge_driver()

        def _rename_to_canonical(path):
            """Rename the downloaded file to the canonical filename if needed."""
            canonical = os.path.join(OUTPUT_DIR, CANONICAL_FILENAME)
            if os.path.abspath(path) != os.path.abspath(canonical):
                if os.path.exists(canonical):
                    os.remove(canonical)
                os.rename(path, canonical)
                print(f"  Renamed to: {CANONICAL_FILENAME}")
                return canonical
            return path

        # ── Step 1: Establish SSO session by visiting the site home ────────
        print(f"Establishing SSO session via: {SITE_URL}")
        driver.get(SITE_URL)
        time.sleep(6)  # allow NTLM/Kerberos handshake to complete
        print(f"  Current page: {driver.current_url[:80]}")

        # ── Step 2: Try downloading via /_layouts/15/download.aspx ─────────
        # This endpoint always sends Content-Disposition: attachment, which
        # reliably triggers Edge's download manager (unlike /$value which may
        # stream inline and be silently discarded in headless mode).
        downloaded_path = None
        for ext in EXCEL_EXTENSIONS:
            server_relative = f"{FILE_FOLDER_RELATIVE_URL}/{FILE_NAME_BASE}{ext}"
            encoded_path = quote(server_relative)
            download_url = f"{SITE_URL}/_layouts/15/download.aspx?SourceUrl={encoded_path}"
            print(f"\nTrying: {download_url}")
            driver.get(download_url)
            time.sleep(5)  # allow redirect + download initiation
            downloaded_path = wait_for_download(before, timeout=45)
            if downloaded_path:
                size_kb = os.path.getsize(downloaded_path) / 1024
                print(f"\nFile downloaded successfully!")
                print(f"  Local : {downloaded_path}")
                print(f"  Size  : {size_kb:.1f} KB")
                downloaded_path = _rename_to_canonical(downloaded_path)
                break

        # ── Step 3: Fallback – REST API /$value ────────────────────────────
        if not downloaded_path:
            print("\nLayout download failed. Trying REST API fallback ...")
            for ext in EXCEL_EXTENSIONS:
                encoded_path = quote(f"{FILE_FOLDER_RELATIVE_URL}/{FILE_NAME_BASE}{ext}")
                download_url = (
                    f"{SITE_URL}/_api/web/GetFileByServerRelativeUrl"
                    f"('{encoded_path}')/$value"
                )
                print(f"  Trying: {download_url}")
                driver.get(download_url)
                time.sleep(5)
                downloaded_path = wait_for_download(before, timeout=30)
                if downloaded_path:
                    size_kb = os.path.getsize(downloaded_path) / 1024
                    print(f"\nFile downloaded successfully!")
                    print(f"  Local : {downloaded_path}")
                    print(f"  Size  : {size_kb:.1f} KB")
                    downloaded_path = _rename_to_canonical(downloaded_path)
                    break

        if not downloaded_path:
            print(
                "\nERROR: Download did not complete within the timeout.\n"
                "Possible causes:\n"
                "  1. SSO login prompt appeared – run on Accenture VPN / corporate network.\n"
                "  2. File name or path changed – update FILE_NAME_BASE or FILE_FOLDER_RELATIVE_URL.\n"
                "  3. SharePoint permissions issue – verify access in browser first."
            )

    except Exception as exc:
        print(f"\nUnexpected error: {exc}")
    finally:
        if driver:
            # Ensure any in-progress download finishes before closing
            deadline = time.time() + DOWNLOAD_TIMEOUT
            while time.time() < deadline:
                partials = (
                    glob.glob(os.path.join(OUTPUT_DIR, "*.crdownload")) +
                    glob.glob(os.path.join(OUTPUT_DIR, "*.tmp"))
                )
                if not partials:
                    break
                time.sleep(1)
            driver.quit()
            print("Done.")


if __name__ == "__main__":
    main()
