#!/usr/bin/env python3
"""
Attendance Tracker – Lightweight HTTP Server (Supabase-backed)

Replaces the old JSON-file storage with Supabase so that all team members
share a single source of truth in real time.

Requires:
    pip install supabase python-dotenv

Environment variables (set in .env in the project root or as OS env vars):
    SUPABASE_URL      – e.g. https://abc123.supabase.co
    SUPABASE_ANON_KEY – the anon/public key from Project Settings → API
"""

# Generated by GitHub Copilot
from http.server import HTTPServer, SimpleHTTPRequestHandler
import json
import os
import sys
import socket
from urllib.parse import urlparse

# ── Load .env from parent directory (MyISP_Tools root) ───────────────────────
_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(_root, '.env'))
except ImportError:
    pass  # python-dotenv not installed; rely on OS env vars

# ── Supabase client ───────────────────────────────────────────────────────────
_SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
_SUPABASE_KEY = os.environ.get('SUPABASE_ANON_KEY', '')
_sb = None

if _SUPABASE_URL and _SUPABASE_KEY:
    try:
        from supabase import create_client
        _sb = create_client(_SUPABASE_URL, _SUPABASE_KEY)
        print(f'✅ Supabase connected: {_SUPABASE_URL}')
    except Exception as e:
        print(f'⚠️  Supabase init failed: {e}')
else:
    print('⚠️  SUPABASE_URL / SUPABASE_ANON_KEY not set – falling back to JSON file')

PORT      = 8080
DATA_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'attendance_data.json')


def _load_from_supabase() -> dict:
    """Return all attendance records as a flat dict keyed by 'member|year|month|day'."""
    if not _sb:
        return {}
    try:
        result = _sb.table('attendance_records').select('*').execute()
        out = {}
        for row in (result.data or []):
            key = f"{row['member_name']}|{row['year']}|{row['month']}|{row['day']}"
            out[key] = row.get('status', '')
        return out
    except Exception as e:
        print(f'⚠️  Supabase load error: {e}')
        return {}


def _save_to_supabase(data: dict):
    """Upsert flat attendance dict back to Supabase."""
    if not _sb:
        return
    try:
        rows = []
        for key, status in data.items():
            parts = key.split('|')
            if len(parts) != 4:
                continue
            member_name, year, month, day = parts
            rows.append({
                'member_name': member_name,
                'year':  int(year),
                'month': int(month),
                'day':   int(day),
                'status': status,
            })
        if not rows:
            return
        CHUNK = 100
        for i in range(0, len(rows), CHUNK):
            _sb.table('attendance_records').upsert(
                rows[i:i + CHUNK],
                on_conflict='member_name,year,month,day'
            ).execute()
    except Exception as e:
        print(f'⚠️  Supabase save error: {e}')


class AttendanceHandler(SimpleHTTPRequestHandler):
    """HTTP handler for attendance data – uses Supabase as primary store."""

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path == '/api/attendance':
            data = _load_from_supabase() if _sb else self._load_json()
            self._json_response(200, data)
            return
        if parsed.path == '/':
            self.path = '/team-attendance-tracker-sharepoint.html'
        return SimpleHTTPRequestHandler.do_GET(self)

    def do_POST(self):
        parsed = urlparse(self.path)
        if parsed.path == '/api/attendance':
            length   = int(self.headers.get('Content-Length', 0))
            raw      = self.rfile.read(length)
            try:
                new_data = json.loads(raw.decode('utf-8'))
                existing = _load_from_supabase() if _sb else self._load_json()
                existing.update(new_data)
                if _sb:
                    _save_to_supabase(existing)
                else:
                    self._save_json(existing)
                self._json_response(200, {'status': 'success', 'message': 'Data saved'})
            except Exception as e:
                self._json_response(500, {'status': 'error', 'message': str(e)})
            return

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def _json_response(self, code: int, payload):
        body = json.dumps(payload, ensure_ascii=False).encode('utf-8')
        self.send_response(code)
        self.send_header('Content-Type', 'application/json; charset=utf-8')
        self.send_header('Content-Length', str(len(body)))
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(body)

    def _load_json(self) -> dict:
        if os.path.exists(DATA_FILE):
            try:
                with open(DATA_FILE, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except Exception:
                pass
        return {}

    def _save_json(self, data: dict):
        with open(DATA_FILE, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def log_message(self, fmt, *args):
        print(f'[{self.log_date_time_string()}] {fmt % args}')


def _get_local_ip() -> str:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return 'localhost'


def main():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    local_ip = _get_local_ip()
    httpd = HTTPServer(('', PORT), AttendanceHandler)

    print('=' * 70)
    print('🚀 Team Attendance Tracker Server (Supabase-backed)')
    print('=' * 70)
    print(f'\n📍 Running on:')
    print(f'   • Local:   http://localhost:{PORT}')
    print(f'   • Network: http://{local_ip}:{PORT}')
    print(f'\n💾 Storage: {"Supabase (" + _SUPABASE_URL + ")" if _sb else "Local JSON file (" + DATA_FILE + ")"}')
    print('\n⚠️  Press Ctrl+C to stop\n')
    print('=' * 70 + '\n')
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print('\n🛑 Server stopped.')


if __name__ == '__main__':
    main()

        
        # API endpoint to get attendance data
        if parsed_path.path == '/api/attendance':
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            
            # Load and return attendance data
            data = self.load_attendance_data()
            self.wfile.write(json.dumps(data).encode())
            return
        
        # Serve the HTML file for root path
        elif parsed_path.path == '/':
            self.path = '/team-attendance-tracker.html'
        
        # Default: serve static files
        return SimpleHTTPRequestHandler.do_GET(self)
    
    def do_POST(self):
        """Handle POST requests"""
        parsed_path = urlparse(self.path)
        
        # API endpoint to save attendance data
        if parsed_path.path == '/api/attendance':
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            
            try:
                # Parse incoming JSON data
                new_data = json.loads(post_data.decode())
                
                # Load existing data
                existing_data = self.load_attendance_data()
                
                # Merge new data with existing
                existing_data.update(new_data)
                
                # Save merged data
                self.save_attendance_data(existing_data)
                
                # Send success response
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(json.dumps({'status': 'success', 'message': 'Data saved'}).encode())
                
            except Exception as e:
                # Send error response
                self.send_response(500)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()
                self.wfile.write(json.dumps({'status': 'error', 'message': str(e)}).encode())
            
            return
        
        # Handle preflight requests for CORS
        self.send_response(200)
        self.end_headers()
    
    def do_OPTIONS(self):
        """Handle OPTIONS requests for CORS"""
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
    
    def load_attendance_data(self):
        """Load attendance data from JSON file"""
        if os.path.exists(DATA_FILE):
            try:
                with open(DATA_FILE, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except:
                return {}
        return {}
    
    def save_attendance_data(self, data):
        """Save attendance data to JSON file"""
        with open(DATA_FILE, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    
    def log_message(self, format, *args):
        """Custom log format with timestamps"""
        print(f"[{self.log_date_time_string()}] {format % args}")


def get_local_ip():
    """Get the local IP address of this machine"""
    try:
        # Connect to external address to determine local IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        local_ip = s.getsockname()[0]
        s.close()
        return local_ip
    except:
        return "localhost"


def main():
    """Start the HTTP server"""
    # Change to the directory where this script is located
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    # Get local IP
    local_ip = get_local_ip()
    
    # Create server
    server_address = ('', PORT)
    httpd = HTTPServer(server_address, AttendanceHandler)
    
    print("=" * 70)
    print("🚀 Team Attendance Tracker Server Started!")
    print("=" * 70)
    print(f"\n📍 Server is running on:")
    print(f"   • Local:   http://localhost:{PORT}")
    print(f"   • Network: http://{local_ip}:{PORT}")
    print("\n📋 Instructions:")
    print("   1. Open the above URL in your browser")
    print("   2. Share the Network URL with your team members")
    print("   3. Everyone can now access the tracker simultaneously")
    print("\n💾 Data Storage:")
    print(f"   • All attendance data is saved in: {DATA_FILE}")
    print(f"   • Location: {os.getcwd()}")
    print("\n⚠️  Keep this window open while team members are using the tracker")
    print("   Press Ctrl+C to stop the server")
    print("=" * 70)
    print("\n✅ Ready! Waiting for connections...\n")
    
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n\n🛑 Server stopped by user")
        httpd.shutdown()


if __name__ == '__main__':
    main()
