// Generated by GitHub Copilot
// ─────────────────────────────────────────────────────────────────────────────
// Supabase credentials for the Attendance Tracker
//
// HOW TO USE:
//   1. Copy this file to:  Attendance/supabase-config.js
//   2. Fill in your project URL and anon key below
//   3. Get the values from: https://supabase.com → Project Settings → API
//
// NOTE: supabase-config.js is listed in .gitignore – your credentials will NOT
//       be committed to the repository.
// ─────────────────────────────────────────────────────────────────────────────

window.SUPABASE_URL      = 'https://your-project-id.supabase.co';
window.SUPABASE_ANON_KEY = 'your-anon-key-here';
