# Generated by GithubCopilot
# Downloads the Release Excel file from SharePoint (mySPTesting site) to the local output directory.
#
# Uses Microsoft Edge browser automation (Selenium) for authentication.
# Edge leverages Windows Integrated Authentication (SSO) on corporate machines
# so no username/password prompt is needed.
#
# Works on corporate networks WITHOUT internet access – uses the msedgedriver.exe
# that is bundled with your Edge installation (no download required).
#
# Requires:
#   pip install selenium

import os
import time
import glob
from pathlib import Path
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.edge.options import Options

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Direct download URL using the SharePoint file UniqueId (from the share link).
# To get a fresh URL: open the file in SharePoint → Share → Copy link,
# then extract the sourcedoc GUID and replace below.
FILE_UNIQUE_ID = "43bc1d9c-c1b6-40c9-bb8c-67af8f1127ec"
SITE_URL       = "https://ts.accenture.com/sites/mySPTesting"

# Direct download URL – no login page shown when Edge has Windows SSO
DOWNLOAD_URL = (
    f"{SITE_URL}/_layouts/15/download.aspx"
    f"?UniqueId={FILE_UNIQUE_ID}"
)

# Fallback: server-relative path if UniqueId URL doesn't resolve
FILE_FOLDER_RELATIVE_URL = (
    "/sites/mySPTesting/Shared Documents/General/"
    "01 - Deliverables/Releases - FY 2025-2026/February"
)
FILE_NAME_BASE     = "21st Feb_Release"
EXCEL_EXTENSIONS   = [".xlsx", ".xlsm", ".xls", ".xlsb"]

# Local destination directory – Edge will download straight here
OUTPUT_DIR = r"C:\Users\vishnu.ramalingam\MyISP_Tools\GHC files\Daily status report"

# How many seconds to wait for the download to finish
DOWNLOAD_TIMEOUT = 60


# ---------------------------------------------------------------------------
# Edge browser helpers
# ---------------------------------------------------------------------------

def find_local_msedgedriver() -> str | None:
    """
    Locate msedgedriver.exe that ships alongside the installed Edge browser.
    Searches the standard Edge installation directories on Windows.
    Returns the full path if found, otherwise None.
    """
    # Common Edge installation roots
    search_roots = [
        r"C:\Program Files (x86)\Microsoft\Edge\Application",
        r"C:\Program Files\Microsoft\Edge\Application",
        os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\Edge\Application"),
    ]
    for root in search_roots:
        if not os.path.isdir(root):
            continue
        # msedgedriver.exe may live inside a version sub-folder or directly in Application
        for candidate in Path(root).rglob("msedgedriver.exe"):
            return str(candidate)
    return None


def build_edge_driver() -> webdriver.Edge:
    """
    Build and return an Edge WebDriver configured to:
      - Download files silently to OUTPUT_DIR (no Save-As dialog)
      - Use Windows Integrated Authentication (SSO) automatically
      - Suppress unnecessary popups
    """
    options = Options()

    # Suppress the Save-As dialog and force download to OUTPUT_DIR
    prefs = {
        "download.default_directory": OUTPUT_DIR,
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "safebrowsing.enabled": True,
        "plugins.always_open_pdf_externally": True,
    }
    options.add_experimental_option("prefs", prefs)

    # Allow Windows Integrated Authentication (Kerberos/NTLM) for Accenture SSO
    options.add_argument("--auth-server-whitelist=*.accenture.com,*.ts.accenture.com")
    options.add_argument("--auth-negotiate-delegate-whitelist=*.accenture.com")

    # Suppress infobars and unnecessary notifications
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_argument("--disable-notifications")
    options.add_argument("--no-first-run")

    # Auto-manage the correct EdgeDriver version
    driver_path = find_local_msedgedriver()
    if driver_path:
        print(f"Using local msedgedriver: {driver_path}")
        service = Service(driver_path)
    else:
        # Selenium 4.6+ has a bundled selenium-manager that finds/caches the driver
        # without needing internet if the driver is already present.
        print("Local msedgedriver not found – using Selenium built-in manager ...")
        service = Service()  # selenium-manager handles discovery
    driver = webdriver.Edge(service=service, options=options)
    return driver


def wait_for_download(filename_hint: str, timeout: int = DOWNLOAD_TIMEOUT) -> str | None:
    """
    Wait until a file matching filename_hint appears in OUTPUT_DIR and is
    fully downloaded (no .crdownload / .tmp partial file).
    Returns the full path of the downloaded file, or None on timeout.
    """
    deadline = time.time() + timeout
    while time.time() < deadline:
        # Look for matching completed files
        for ext in EXCEL_EXTENSIONS:
            pattern = os.path.join(OUTPUT_DIR, f"*{FILE_NAME_BASE}*{ext}")
            matches = glob.glob(pattern)
            # Filter out partial downloads
            complete = [f for f in matches if not f.endswith((".crdownload", ".tmp"))]
            if complete:
                return complete[0]
        # Also check if any new Excel file appeared (name may differ)
        for ext in EXCEL_EXTENSIONS:
            pattern = os.path.join(OUTPUT_DIR, f"*{ext}")
            matches = glob.glob(pattern)
            complete = [
                f for f in matches
                if not f.endswith((".crdownload", ".tmp"))
                and (time.time() - os.path.getmtime(f)) < timeout
            ]
            if complete:
                return sorted(complete, key=os.path.getmtime)[-1]
        time.sleep(1)
    return None


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 70)
    print("SHAREPOINT FILE DOWNLOADER  (Microsoft Edge / Windows SSO)")
    print("=" * 70)
    print(f"\nDownload URL : {DOWNLOAD_URL}")
    print(f"Destination  : {OUTPUT_DIR}\n")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Record files present before download so we can identify the new one
    before = set(
        f for ext in EXCEL_EXTENSIONS
        for f in glob.glob(os.path.join(OUTPUT_DIR, f"*{ext}"))
    )

    driver = None
    try:
        print("Launching Edge browser ...")
        driver = build_edge_driver()

        print(f"Navigating to download URL ...")
        driver.get(DOWNLOAD_URL)

        # Give the browser a moment to process SSO and start the download
        print(f"Waiting up to {DOWNLOAD_TIMEOUT}s for download to complete ...")
        time.sleep(3)  # brief pause for SSO redirect + download to initiate

        downloaded_path = wait_for_download(FILE_NAME_BASE)

        if downloaded_path:
            print(f"\nFile downloaded successfully!")
            print(f"  Local : {downloaded_path}")
        else:
            # Try fallback URLs for each extension
            print("\nDirect UniqueId URL did not trigger a download. Trying fallback paths ...")
            for ext in EXCEL_EXTENSIONS:
                fallback_url = (
                    f"{SITE_URL}/_api/web/GetFileByServerRelativeUrl"
                    f"('{FILE_FOLDER_RELATIVE_URL}/{FILE_NAME_BASE}{ext}')/$value"
                )
                print(f"  Trying: {fallback_url}")
                driver.get(fallback_url)
                time.sleep(3)
                downloaded_path = wait_for_download(FILE_NAME_BASE, timeout=20)
                if downloaded_path:
                    print(f"\nFile downloaded successfully!")
                    print(f"  Local : {downloaded_path}")
                    break

            if not downloaded_path:
                print(
                    f"\nERROR: Download did not complete within {DOWNLOAD_TIMEOUT}s.\n"
                    "Possible causes:\n"
                    "  1. SSO login prompt appeared – run on Accenture VPN / corporate network.\n"
                    "  2. File name or path changed – update FILE_NAME_BASE or FILE_UNIQUE_ID.\n"
                    "  3. SharePoint permissions issue – verify access in browser first."
                )

    except Exception as exc:
        print(f"\nUnexpected error: {exc}")
    finally:
        if driver:
            time.sleep(2)   # ensure download finishes before closing browser
            driver.quit()
            print("Browser closed.")


if __name__ == "__main__":
    main()
