"""
Centralized Configuration for Hot Fix Daily Status Report Scripts
==================================================================

IMPORTANT: This is the ONLY file you need to edit when sharing code with others!

When moving this project to a different system:
1. Output files are saved locally in the Hot_Fix_Daily_Status_Report folder
2. Update POD_MAPPING_PATH if using a different POD mapping file location
3. All other scripts will automatically use these paths

"""

import os

# ============================================================================
# MAIN CONFIGURATION - EDIT THESE PATHS ONLY
# ============================================================================

# Get current user's profile directory (works on any Windows machine)
USER_PROFILE = os.environ.get('USERPROFILE', os.path.expanduser('~'))

# Get the project root directory (parent of Hot_Fix_Daily_Status_Report)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

# Base output directory where all generated files will be saved
# Use SCRIPT_DIR to keep Hot Fix outputs local to the project folder
OUTPUT_DIR = SCRIPT_DIR

# POD Mapping sheet location - using project's Common_Files folder (works on any machine)
POD_MAPPING_PATH = os.path.join(PROJECT_ROOT, "Common_Files", "POD Mapping sheet_Updated.csv")

# ============================================================================
# DERIVED PATHS (Do not edit - these are auto-generated from OUTPUT_DIR)
# ============================================================================

# Input files (downloaded from SharePoint)
PT_STATUS_FILE = os.path.join(OUTPUT_DIR, "PT Status excel.xlsx")
UAT_DETAILED_REPORT_FILE = os.path.join(OUTPUT_DIR, "UAT Release Detailed Report.xlsx")

# Output files (generated by scripts)
PO_DETAILS_FILE = os.path.join(OUTPUT_DIR, "PO Details.xlsx")
OPEN_BUG_SUMMARY_FILE = os.path.join(OUTPUT_DIR, "Open_Bug_summary.xlsx")
STORY_SUMMARY_FILE = os.path.join(OUTPUT_DIR, "Story_summary.xlsx")
OVERALL_DEFECT_SUMMARY_FILE = os.path.join(OUTPUT_DIR, "Overall_Defect_Summary.xlsx")
DAILY_STATUS_DASHBOARD_FILE = os.path.join(OUTPUT_DIR, "Daily_Status_Dashboard.html")

# Ensure output directory exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================================
# USAGE INSTRUCTIONS
# ============================================================================
"""
To use this config in any script:

    from config import OUTPUT_DIR, POD_MAPPING_PATH
    
    # Use OUTPUT_DIR for file operations
    output_file = os.path.join(OUTPUT_DIR, "my_output.xlsx")
    
    # Use POD_MAPPING_PATH for mapping file
    mapping_df = pd.read_csv(POD_MAPPING_PATH)
"""
