"""
Centralized Configuration for Daily Status Report Scripts
==========================================================

IMPORTANT: This is the ONLY file you need to edit when sharing code with others!

When moving this project to a different system:
1. Update OUTPUT_DIR to your desired output folder path
2. Update POD_MAPPING_PATH to your POD mapping CSV file location
3. All other scripts will automatically use these paths

"""

import os
from pathlib import Path

# ============================================================================
# MAIN CONFIGURATION - AUTO-DETECTED PATHS (works on any machine)
# ============================================================================

_USER_HOME = Path.home()
# Project root = two levels up from this config.py (i.e. MyISP_Tools/)
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
# Script directory (Main_Release_Daily_Status_Report)
_SCRIPT_DIR = Path(__file__).resolve().parent

def _find_first_existing(*candidates):
    """Return the first path that exists, or the last candidate as default."""
    for p in candidates:
        if Path(p).exists():
            return str(p)
    return str(candidates[-1])

# Base output directory - searches candidate locations in order
# Priority: 1. Script dir (works in Docker), 2. GHC files in project, 3. GHC files in user home
OUTPUT_DIR = _find_first_existing(
    _SCRIPT_DIR,  # Primary: Use script directory itself (works in Docker)
    _PROJECT_ROOT / "GHC files" / "Daily status report - Integrated",
    _USER_HOME / "GHC files" / "Daily status report - Integrated",
)

# POD Mapping sheet - searches candidate locations in order
POD_MAPPING_PATH = _find_first_existing(
    _PROJECT_ROOT / "GHC files" / "POC mapping" / "POD Mapping sheet_Updated.csv",
    _PROJECT_ROOT / "Common_Files" / "POD Mapping sheet_Updated.csv",
    _USER_HOME / "GHC files" / "POC mapping" / "POD Mapping sheet_Updated.csv",
    _USER_HOME / "OneDrive - Accenture" / "Documents" / "GHC files" / "GHC files" / "POD Mapping sheet_Updated.csv",
)

# ============================================================================
# DERIVED PATHS (Do not edit - these are auto-generated from OUTPUT_DIR)
# ============================================================================

# Input files (downloaded from SharePoint)
PT_STATUS_FILE = os.path.join(OUTPUT_DIR, "PT Status excel.xlsx")
UAT_DETAILED_REPORT_FILE = os.path.join(OUTPUT_DIR, "UAT Release Detailed Report.xlsx")

# Output files (generated by scripts)
PO_DETAILS_FILE = os.path.join(OUTPUT_DIR, "PO Details.xlsx")
OPEN_BUG_SUMMARY_FILE = os.path.join(OUTPUT_DIR, "Open_Bug_summary.xlsx")
STORY_SUMMARY_FILE = os.path.join(OUTPUT_DIR, "Story_summary.xlsx")
OVERALL_DEFECT_SUMMARY_FILE = os.path.join(OUTPUT_DIR, "Overall_Defect_Summary.xlsx")
DAILY_STATUS_DASHBOARD_FILE = os.path.join(OUTPUT_DIR, "Daily_Status_Dashboard.html")

# Ensure output directory exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================================
# USAGE INSTRUCTIONS
# ============================================================================
"""
To use this config in any script:

    from config import OUTPUT_DIR, POD_MAPPING_PATH
    
    # Use OUTPUT_DIR for file operations
    output_file = os.path.join(OUTPUT_DIR, "my_output.xlsx")
    
    # Use POD_MAPPING_PATH for mapping file
    mapping_df = pd.read_csv(POD_MAPPING_PATH)
"""
